import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author wonjerry
 */
public class SideBarPanel extends javax.swing.JPanel {

    /**
     * Creates new form SideBarPanel
     */
    public SideBarPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drawClassPanel = new javax.swing.JPanel();
        addClassBtn = new javax.swing.JButton();
        drawArrowPanel = new javax.swing.JPanel();
        addDependencyArrowBtn = new javax.swing.JButton();
        addExtendsArrowBtn = new javax.swing.JButton();
        viewDocumentPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        setPreferredSize(new java.awt.Dimension(300, 933));

        drawClassPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addClassBtn.setText("addClassBtn");
		ImageIcon classIcon = new ImageIcon(System.getProperty("user.dir") + "\\images\\classIcon2.png");

        addClassBtn.setIcon(classIcon);

        javax.swing.GroupLayout drawClassPanelLayout = new javax.swing.GroupLayout(drawClassPanel);
        drawClassPanel.setLayout(drawClassPanelLayout);
        drawClassPanelLayout.setHorizontalGroup(
            drawClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drawClassPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addClassBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );
        drawClassPanelLayout.setVerticalGroup(
            drawClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drawClassPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addClassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        drawArrowPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addDependencyArrowBtn.setText("addDependencyArrowBtn");
        ImageIcon dependencyArrowIcon = new ImageIcon(System.getProperty("user.dir") + "\\images\\dependencyarrow.png");
        addClassBtn.setIcon(dependencyArrowIcon);

        addExtendsArrowBtn.setText("addExtendsArrowBtn");
        ImageIcon extendsArrowIcon = new ImageIcon(System.getProperty("user.dir") + "\\images\\extendsarrow.png");
        addClassBtn.setIcon(extendsArrowIcon);

        javax.swing.GroupLayout drawArrowPanelLayout = new javax.swing.GroupLayout(drawArrowPanel);
        drawArrowPanel.setLayout(drawArrowPanelLayout);
        drawArrowPanelLayout.setHorizontalGroup(
            drawArrowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drawArrowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(drawArrowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addExtendsArrowBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addDependencyArrowBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        drawArrowPanelLayout.setVerticalGroup(
            drawArrowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drawArrowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addDependencyArrowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addExtendsArrowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        viewDocumentPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout viewDocumentPanelLayout = new javax.swing.GroupLayout(viewDocumentPanel);
        viewDocumentPanel.setLayout(viewDocumentPanelLayout);
        viewDocumentPanelLayout.setHorizontalGroup(
            viewDocumentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        viewDocumentPanelLayout.setVerticalGroup(
            viewDocumentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(drawClassPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(drawArrowPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(viewDocumentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(drawClassPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drawArrowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewDocumentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClassBtn;
    private javax.swing.JButton addDependencyArrowBtn;
    private javax.swing.JButton addExtendsArrowBtn;
    private javax.swing.JPanel drawClassPanel;
    private javax.swing.JPanel drawArrowPanel;
    private javax.swing.JPanel viewDocumentPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
